// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgqfpmvpmqqdblpvrbpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpncWZwbXZwbXFxZGJscHZyYnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODI3ODMsImV4cCI6MjA2NDQ1ODc4M30.TCuYLDSYDsz30Ynqe8j4JuBkCQhVesU7oMaLrBe1Fvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);